#-Dspring.profiles.active=dev -Xmx128M -Xms128M
server:
  port: 8083
spring:
  application:
    name: cashtracker-stocks
  datasource:
    url: jdbc:mysql://localhost:3306/stocks?useSSL=false
    username: root
    password: Dip4rudp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/